config/routes.rb
Rails.application.routes.draw do
  resources :lists
  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemController < ApplicationController

  def show
    render :show
  end

  def new
    render :new
  end

  def edit
    render :edit
  end

  def create

  end
  
  def update
  end


  def permit_params
    params.require(:item).permit()
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index #get /lists
    @lists = List.all
    @list = List.new
    render :index
  end

    def show
      @list = List.find_by(id: params[:id])
      render :show
    end

    def create
      @list = List.new(list_params)
      if @list.valid?
        @list.save
        redirect_to lists_path
      else
        render :show
      end

    end

    private

    def list_params
      params.require(:list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssetsAndManagingLists</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<%= yield %>


  </body>
</html>

app/views/lists/index.html.erb
<!DOCTYPE html>

  <body>
    <section class="todoapp">
   			<header class="header">
   				<h1>Your lists</h1>
          <%= form_for(@list) do |f| %>
            <%= f.text_field :name, placeholder: 'Add a new list', class:"new-todo", autofocus: "" %>
          <% end %>

   			</header>

   			<section class="main" >
          <ul class = "todo-list">
            <% sorted_lists = @lists.sort_by{|list| list.created_at}.reverse %>
            <% sorted_lists.each do |list| %>
            <li>
              <div class = "view">
                <label><%= link_to list.name, list_path(list.id) %></label>
              </div>
            </li>
            <% end %>
          </ul>
   			</section>

   			<footer class="footer" >
     			</footer>
   		</section>

  </body>
</html>

app/views/lists/show.html.erb
<!DOCTYPE html>

<section class="todoapp">
    <header class="header">
        <h1><%= @list.name%></h1>
        <input class="new-todo" placeholder="Add an item" autofocus="">
    </header>

    <section class="main" >
        <ul class = "todo-list">
            <li>
                <div class = "view">
                    <label>Ice cream</lable>
                </div>
            </li>

            <li>
                <div class = "view">
                    <label>cookies</lable>
                </div>
            </li>

            <li>
                <div class = "view">
                    <label>Milk</lable>
                </div>
            </li>

        </ul>
    </section>

    <footer class="footer" >
    </footer>
</section>